// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tables.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvestorType int32

const (
	InvestorType_banks                InvestorType = 0
	InvestorType_angel_Investors      InvestorType = 1
	InvestorType_peer_to_peer_lenders InvestorType = 2
	InvestorType_venture_capitalists  InvestorType = 3
	InvestorType_personal_investors   InvestorType = 4
)

var InvestorType_name = map[int32]string{
	0: "banks",
	1: "angel_Investors",
	2: "peer_to_peer_lenders",
	3: "venture_capitalists",
	4: "personal_investors",
}

var InvestorType_value = map[string]int32{
	"banks":                0,
	"angel_Investors":      1,
	"peer_to_peer_lenders": 2,
	"venture_capitalists":  3,
	"personal_investors":   4,
}

func (x InvestorType) String() string {
	return proto.EnumName(InvestorType_name, int32(x))
}

func (InvestorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{0}
}

type InvestmentStage int32

const (
	InvestmentStage_seed_capital                              InvestmentStage = 0
	InvestmentStage_startup_capital                           InvestmentStage = 1
	InvestmentStage_early_first_second_stage_capital          InvestmentStage = 2
	InvestmentStage_expansion_second_third_stage_capital      InvestmentStage = 3
	InvestmentStage_mezzanine_bridge_pre_public_stage_capital InvestmentStage = 4
)

var InvestmentStage_name = map[int32]string{
	0: "seed_capital",
	1: "startup_capital",
	2: "early_first_second_stage_capital",
	3: "expansion_second_third_stage_capital",
	4: "mezzanine_bridge_pre_public_stage_capital",
}

var InvestmentStage_value = map[string]int32{
	"seed_capital":                              0,
	"startup_capital":                           1,
	"early_first_second_stage_capital":          2,
	"expansion_second_third_stage_capital":      3,
	"mezzanine_bridge_pre_public_stage_capital": 4,
}

func (x InvestmentStage) String() string {
	return proto.EnumName(InvestmentStage_name, int32(x))
}

func (InvestmentStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{1}
}

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserAccountType      string               `protobuf:"bytes,5,opt,name=user_account_type,json=userAccountType,proto3" json:"user_account_type,omitempty"`
	FirstName            string               `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	UserName             string               `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Gender               string               `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Languages            string               `protobuf:"bytes,10,opt,name=languages,proto3" json:"languages,omitempty"`
	Password             string               `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmed    string               `protobuf:"bytes,12,opt,name=password_confirmed,json=passwordConfirmed,proto3" json:"password_confirmed,omitempty"`
	Age                  int32                `protobuf:"varint,13,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate            string               `protobuf:"bytes,14,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,15,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email                string               `protobuf:"bytes,16,opt,name=email,proto3" json:"email,omitempty"`
	Intent               string               `protobuf:"bytes,17,opt,name=intent,proto3" json:"intent,omitempty"`
	ProfileId            *Profile             `protobuf:"bytes,18,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ResetToken           string               `protobuf:"bytes,19,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	ResetTokenExpiration *timestamp.Timestamp `protobuf:"bytes,20,opt,name=reset_token_expiration,json=resetTokenExpiration,proto3" json:"reset_token_expiration,omitempty"`
	SubscriptionsId      []*Subscriptions     `protobuf:"bytes,21,rep,name=subscriptions_id,json=subscriptionsId,proto3" json:"subscriptions_id,omitempty"`
	IsActive             bool                 `protobuf:"varint,22,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetUserAccountType() string {
	if m != nil {
		return m.UserAccountType
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetLanguages() string {
	if m != nil {
		return m.Languages
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPasswordConfirmed() string {
	if m != nil {
		return m.PasswordConfirmed
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIntent() string {
	if m != nil {
		return m.Intent
	}
	return ""
}

func (m *User) GetProfileId() *Profile {
	if m != nil {
		return m.ProfileId
	}
	return nil
}

func (m *User) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

func (m *User) GetResetTokenExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.ResetTokenExpiration
	}
	return nil
}

func (m *User) GetSubscriptionsId() []*Subscriptions {
	if m != nil {
		return m.SubscriptionsId
	}
	return nil
}

func (m *User) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

// Based on user
type Profile struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Bio                  string               `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	ExperienceId         []*Experience        `protobuf:"bytes,6,rep,name=experience_id,json=experienceId,proto3" json:"experience_id,omitempty"`
	AddressId            *Address             `protobuf:"bytes,7,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	EducationId          []*Education         `protobuf:"bytes,8,rep,name=education_id,json=educationId,proto3" json:"education_id,omitempty"`
	Skills               []string             `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	TeamId               *Team                `protobuf:"bytes,10,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	GroupId              []*Group             `protobuf:"bytes,11,rep,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SocialMedia          *SocialMedia         `protobuf:"bytes,12,opt,name=social_media,json=socialMedia,proto3" json:"social_media,omitempty"`
	SettingsId           *Settings            `protobuf:"bytes,13,opt,name=settings_id,json=settingsId,proto3" json:"settings_id,omitempty"`
	ProfileType          string               `protobuf:"bytes,14,opt,name=profile_type,json=profileType,proto3" json:"profile_type,omitempty"`
	Nationality          string               `protobuf:"bytes,15,opt,name=nationality,proto3" json:"nationality,omitempty"`
	AvatarUrl            string               `protobuf:"bytes,16,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Profile) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Profile) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Profile) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Profile) GetExperienceId() []*Experience {
	if m != nil {
		return m.ExperienceId
	}
	return nil
}

func (m *Profile) GetAddressId() *Address {
	if m != nil {
		return m.AddressId
	}
	return nil
}

func (m *Profile) GetEducationId() []*Education {
	if m != nil {
		return m.EducationId
	}
	return nil
}

func (m *Profile) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Profile) GetTeamId() *Team {
	if m != nil {
		return m.TeamId
	}
	return nil
}

func (m *Profile) GetGroupId() []*Group {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *Profile) GetSocialMedia() *SocialMedia {
	if m != nil {
		return m.SocialMedia
	}
	return nil
}

func (m *Profile) GetSettingsId() *Settings {
	if m != nil {
		return m.SettingsId
	}
	return nil
}

func (m *Profile) GetProfileType() string {
	if m != nil {
		return m.ProfileType
	}
	return ""
}

func (m *Profile) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

func (m *Profile) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

// Group entities withold a many to many relationship with the User entities
type Group struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Type                 string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Bio                  string               `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Tags                 []string             `protobuf:"bytes,8,rep,name=Tags,proto3" json:"Tags,omitempty"`
	NumberOfMembers      int32                `protobuf:"varint,9,opt,name=number_of_members,json=numberOfMembers,proto3" json:"number_of_members,omitempty"`
	GroupMembers         []*User              `protobuf:"bytes,10,rep,name=group_members,json=groupMembers,proto3" json:"group_members,omitempty"`
	IsPublic             bool                 `protobuf:"varint,11,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	Admin                *User                `protobuf:"bytes,12,opt,name=Admin,proto3" json:"Admin,omitempty"`
	AvatarUrl            string               `protobuf:"bytes,13,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{2}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Group) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Group) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Group) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Group) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Group) GetNumberOfMembers() int32 {
	if m != nil {
		return m.NumberOfMembers
	}
	return 0
}

func (m *Group) GetGroupMembers() []*User {
	if m != nil {
		return m.GroupMembers
	}
	return nil
}

func (m *Group) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *Group) GetAdmin() *User {
	if m != nil {
		return m.Admin
	}
	return nil
}

func (m *Group) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type Team struct {
	Id        int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name      string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Comma separated values of tags
	Tags                 []string             `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Email                string               `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Type                 string               `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Industry             string               `protobuf:"bytes,9,opt,name=industry,proto3" json:"industry,omitempty"`
	FoundedDate          *timestamp.Timestamp `protobuf:"bytes,10,opt,name=founded_date,json=foundedDate,proto3" json:"founded_date,omitempty"`
	NumberOfEmployees    int32                `protobuf:"varint,11,opt,name=number_of_employees,json=numberOfEmployees,proto3" json:"number_of_employees,omitempty"`
	HeadquartersId       *Address             `protobuf:"bytes,12,opt,name=headquarters_id,json=headquartersId,proto3" json:"headquarters_id,omitempty"`
	Members              []*User              `protobuf:"bytes,13,rep,name=members,proto3" json:"members,omitempty"`
	Advisors             []*User              `protobuf:"bytes,14,rep,name=advisors,proto3" json:"advisors,omitempty"`
	SocialMedia          *SocialMedia         `protobuf:"bytes,15,opt,name=social_media,json=socialMedia,proto3" json:"social_media,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,16,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password             string               `protobuf:"bytes,17,opt,name=password,proto3" json:"password,omitempty"`
	TeamProfileId        *TeamProfile         `protobuf:"bytes,18,opt,name=team_profile_id,json=teamProfileId,proto3" json:"team_profile_id,omitempty"`
	Subscriptions        []*Subscriptions     `protobuf:"bytes,19,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	IsActive             bool                 `protobuf:"varint,20,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ResetToken           string               `protobuf:"bytes,21,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	ResetTokenExpiration *timestamp.Timestamp `protobuf:"bytes,22,opt,name=reset_token_expiration,json=resetTokenExpiration,proto3" json:"reset_token_expiration,omitempty"`
	AdminId              *User                `protobuf:"bytes,23,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Bio                  string               `protobuf:"bytes,24,opt,name=bio,proto3" json:"bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{3}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Team) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Team) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Team) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Team) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Team) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Team) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

func (m *Team) GetFoundedDate() *timestamp.Timestamp {
	if m != nil {
		return m.FoundedDate
	}
	return nil
}

func (m *Team) GetNumberOfEmployees() int32 {
	if m != nil {
		return m.NumberOfEmployees
	}
	return 0
}

func (m *Team) GetHeadquartersId() *Address {
	if m != nil {
		return m.HeadquartersId
	}
	return nil
}

func (m *Team) GetMembers() []*User {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Team) GetAdvisors() []*User {
	if m != nil {
		return m.Advisors
	}
	return nil
}

func (m *Team) GetSocialMedia() *SocialMedia {
	if m != nil {
		return m.SocialMedia
	}
	return nil
}

func (m *Team) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Team) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Team) GetTeamProfileId() *TeamProfile {
	if m != nil {
		return m.TeamProfileId
	}
	return nil
}

func (m *Team) GetSubscriptions() []*Subscriptions {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func (m *Team) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Team) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

func (m *Team) GetResetTokenExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.ResetTokenExpiration
	}
	return nil
}

func (m *Team) GetAdminId() *User {
	if m != nil {
		return m.AdminId
	}
	return nil
}

func (m *Team) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

type TeamProfile struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SettingsId           *Settings            `protobuf:"bytes,5,opt,name=settings_id,json=settingsId,proto3" json:"settings_id,omitempty"`
	InvestorDetailId     *InvestorDetail      `protobuf:"bytes,6,opt,name=investor_detail_id,json=investorDetailId,proto3" json:"investor_detail_id,omitempty"`
	StartupDetailId      *StartupDetail       `protobuf:"bytes,7,opt,name=startup_detail_id,json=startupDetailId,proto3" json:"startup_detail_id,omitempty"`
	MediaId              *Media               `protobuf:"bytes,8,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TeamProfile) Reset()         { *m = TeamProfile{} }
func (m *TeamProfile) String() string { return proto.CompactTextString(m) }
func (*TeamProfile) ProtoMessage()    {}
func (*TeamProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{4}
}

func (m *TeamProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamProfile.Unmarshal(m, b)
}
func (m *TeamProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamProfile.Marshal(b, m, deterministic)
}
func (m *TeamProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamProfile.Merge(m, src)
}
func (m *TeamProfile) XXX_Size() int {
	return xxx_messageInfo_TeamProfile.Size(m)
}
func (m *TeamProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamProfile.DiscardUnknown(m)
}

var xxx_messageInfo_TeamProfile proto.InternalMessageInfo

func (m *TeamProfile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TeamProfile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TeamProfile) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *TeamProfile) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TeamProfile) GetSettingsId() *Settings {
	if m != nil {
		return m.SettingsId
	}
	return nil
}

func (m *TeamProfile) GetInvestorDetailId() *InvestorDetail {
	if m != nil {
		return m.InvestorDetailId
	}
	return nil
}

func (m *TeamProfile) GetStartupDetailId() *StartupDetail {
	if m != nil {
		return m.StartupDetailId
	}
	return nil
}

func (m *TeamProfile) GetMediaId() *Media {
	if m != nil {
		return m.MediaId
	}
	return nil
}

type InvestorDetail struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	InvestorType         InvestorType         `protobuf:"varint,5,opt,name=investor_type,json=investorType,proto3,enum=InvestorType" json:"investor_type,omitempty"`
	InvestmentStage      InvestmentStage      `protobuf:"varint,6,opt,name=investment_stage,json=investmentStage,proto3,enum=InvestmentStage" json:"investment_stage,omitempty"`
	NumberOfExits        int32                `protobuf:"varint,7,opt,name=number_of_exits,json=numberOfExits,proto3" json:"number_of_exits,omitempty"`
	NumberOfInvestments  int32                `protobuf:"varint,8,opt,name=number_of_investments,json=numberOfInvestments,proto3" json:"number_of_investments,omitempty"`
	NumberOfFunds        int32                `protobuf:"varint,9,opt,name=number_of_funds,json=numberOfFunds,proto3" json:"number_of_funds,omitempty"`
	InvestmentsId        []*Investment        `protobuf:"bytes,10,rep,name=investments_id,json=investmentsId,proto3" json:"investments_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InvestorDetail) Reset()         { *m = InvestorDetail{} }
func (m *InvestorDetail) String() string { return proto.CompactTextString(m) }
func (*InvestorDetail) ProtoMessage()    {}
func (*InvestorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{5}
}

func (m *InvestorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvestorDetail.Unmarshal(m, b)
}
func (m *InvestorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvestorDetail.Marshal(b, m, deterministic)
}
func (m *InvestorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvestorDetail.Merge(m, src)
}
func (m *InvestorDetail) XXX_Size() int {
	return xxx_messageInfo_InvestorDetail.Size(m)
}
func (m *InvestorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_InvestorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_InvestorDetail proto.InternalMessageInfo

func (m *InvestorDetail) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InvestorDetail) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *InvestorDetail) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *InvestorDetail) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *InvestorDetail) GetInvestorType() InvestorType {
	if m != nil {
		return m.InvestorType
	}
	return InvestorType_banks
}

func (m *InvestorDetail) GetInvestmentStage() InvestmentStage {
	if m != nil {
		return m.InvestmentStage
	}
	return InvestmentStage_seed_capital
}

func (m *InvestorDetail) GetNumberOfExits() int32 {
	if m != nil {
		return m.NumberOfExits
	}
	return 0
}

func (m *InvestorDetail) GetNumberOfInvestments() int32 {
	if m != nil {
		return m.NumberOfInvestments
	}
	return 0
}

func (m *InvestorDetail) GetNumberOfFunds() int32 {
	if m != nil {
		return m.NumberOfFunds
	}
	return 0
}

func (m *InvestorDetail) GetInvestmentsId() []*Investment {
	if m != nil {
		return m.InvestmentsId
	}
	return nil
}

type StartupDetail struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TotalFunding         int32                `protobuf:"varint,5,opt,name=total_funding,json=totalFunding,proto3" json:"total_funding,omitempty"`
	LatestRoundFunding   int32                `protobuf:"varint,6,opt,name=latest_round_funding,json=latestRoundFunding,proto3" json:"latest_round_funding,omitempty"`
	LatestRound          string               `protobuf:"bytes,7,opt,name=latest_round,json=latestRound,proto3" json:"latest_round,omitempty"`
	LatestRoundEndDate   *timestamp.Timestamp `protobuf:"bytes,8,opt,name=latest_round_end_date,json=latestRoundEndDate,proto3" json:"latest_round_end_date,omitempty"`
	FundingType          string               `protobuf:"bytes,9,opt,name=funding_type,json=fundingType,proto3" json:"funding_type,omitempty"`
	CompanyName          string               `protobuf:"bytes,10,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StartupDetail) Reset()         { *m = StartupDetail{} }
func (m *StartupDetail) String() string { return proto.CompactTextString(m) }
func (*StartupDetail) ProtoMessage()    {}
func (*StartupDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{6}
}

func (m *StartupDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupDetail.Unmarshal(m, b)
}
func (m *StartupDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupDetail.Marshal(b, m, deterministic)
}
func (m *StartupDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupDetail.Merge(m, src)
}
func (m *StartupDetail) XXX_Size() int {
	return xxx_messageInfo_StartupDetail.Size(m)
}
func (m *StartupDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupDetail.DiscardUnknown(m)
}

var xxx_messageInfo_StartupDetail proto.InternalMessageInfo

func (m *StartupDetail) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StartupDetail) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *StartupDetail) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *StartupDetail) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *StartupDetail) GetTotalFunding() int32 {
	if m != nil {
		return m.TotalFunding
	}
	return 0
}

func (m *StartupDetail) GetLatestRoundFunding() int32 {
	if m != nil {
		return m.LatestRoundFunding
	}
	return 0
}

func (m *StartupDetail) GetLatestRound() string {
	if m != nil {
		return m.LatestRound
	}
	return ""
}

func (m *StartupDetail) GetLatestRoundEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.LatestRoundEndDate
	}
	return nil
}

func (m *StartupDetail) GetFundingType() string {
	if m != nil {
		return m.FundingType
	}
	return ""
}

func (m *StartupDetail) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type Settings struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	LastLoginLocation    string               `protobuf:"bytes,6,opt,name=last_login_location,json=lastLoginLocation,proto3" json:"last_login_location,omitempty"`
	NotificationId       *Notification        `protobuf:"bytes,7,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	PrivacyId            *Privacy             `protobuf:"bytes,8,opt,name=privacy_id,json=privacyId,proto3" json:"privacy_id,omitempty"`
	PaymentId            *Payments            `protobuf:"bytes,9,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Settings) Reset()         { *m = Settings{} }
func (m *Settings) String() string { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()    {}
func (*Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{7}
}

func (m *Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settings.Unmarshal(m, b)
}
func (m *Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settings.Marshal(b, m, deterministic)
}
func (m *Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settings.Merge(m, src)
}
func (m *Settings) XXX_Size() int {
	return xxx_messageInfo_Settings.Size(m)
}
func (m *Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_Settings proto.InternalMessageInfo

func (m *Settings) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Settings) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Settings) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Settings) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Settings) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Settings) GetLastLoginLocation() string {
	if m != nil {
		return m.LastLoginLocation
	}
	return ""
}

func (m *Settings) GetNotificationId() *Notification {
	if m != nil {
		return m.NotificationId
	}
	return nil
}

func (m *Settings) GetPrivacyId() *Privacy {
	if m != nil {
		return m.PrivacyId
	}
	return nil
}

func (m *Settings) GetPaymentId() *Payments {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

type LoginActivity struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Location             *Address `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginActivity) Reset()         { *m = LoginActivity{} }
func (m *LoginActivity) String() string { return proto.CompactTextString(m) }
func (*LoginActivity) ProtoMessage()    {}
func (*LoginActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{8}
}

func (m *LoginActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginActivity.Unmarshal(m, b)
}
func (m *LoginActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginActivity.Marshal(b, m, deterministic)
}
func (m *LoginActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginActivity.Merge(m, src)
}
func (m *LoginActivity) XXX_Size() int {
	return xxx_messageInfo_LoginActivity.Size(m)
}
func (m *LoginActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginActivity.DiscardUnknown(m)
}

var xxx_messageInfo_LoginActivity proto.InternalMessageInfo

func (m *LoginActivity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginActivity) GetLocation() *Address {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LoginActivity) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type Payments struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	DebitCard            *Card                `protobuf:"bytes,6,opt,name=debit_card,json=debitCard,proto3" json:"debit_card,omitempty"`
	CreditCard           *Card                `protobuf:"bytes,7,opt,name=credit_card,json=creditCard,proto3" json:"credit_card,omitempty"`
	Pin                  *Pin                 `protobuf:"bytes,8,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Payments) Reset()         { *m = Payments{} }
func (m *Payments) String() string { return proto.CompactTextString(m) }
func (*Payments) ProtoMessage()    {}
func (*Payments) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{9}
}

func (m *Payments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payments.Unmarshal(m, b)
}
func (m *Payments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payments.Marshal(b, m, deterministic)
}
func (m *Payments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payments.Merge(m, src)
}
func (m *Payments) XXX_Size() int {
	return xxx_messageInfo_Payments.Size(m)
}
func (m *Payments) XXX_DiscardUnknown() {
	xxx_messageInfo_Payments.DiscardUnknown(m)
}

var xxx_messageInfo_Payments proto.InternalMessageInfo

func (m *Payments) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payments) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Payments) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Payments) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Payments) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Payments) GetDebitCard() *Card {
	if m != nil {
		return m.DebitCard
	}
	return nil
}

func (m *Payments) GetCreditCard() *Card {
	if m != nil {
		return m.CreditCard
	}
	return nil
}

func (m *Payments) GetPin() *Pin {
	if m != nil {
		return m.Pin
	}
	return nil
}

type Card struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CardNumber           string               `protobuf:"bytes,6,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	SecurityCode         string               `protobuf:"bytes,7,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	CardZipCode          string               `protobuf:"bytes,8,opt,name=card_zip_code,json=cardZipCode,proto3" json:"card_zip_code,omitempty"`
	FullName             string               `protobuf:"bytes,9,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	City                 string               `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	State                string               `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	Zipcode              string               `protobuf:"bytes,12,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	Address              string               `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{10}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Card) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Card) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Card) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Card) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Card) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *Card) GetSecurityCode() string {
	if m != nil {
		return m.SecurityCode
	}
	return ""
}

func (m *Card) GetCardZipCode() string {
	if m != nil {
		return m.CardZipCode
	}
	return ""
}

func (m *Card) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Card) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Card) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Card) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

func (m *Card) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Pin struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	PinEnabled           bool                 `protobuf:"varint,6,opt,name=pin_enabled,json=pinEnabled,proto3" json:"pin_enabled,omitempty"`
	Pin                  string               `protobuf:"bytes,7,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pin) Reset()         { *m = Pin{} }
func (m *Pin) String() string { return proto.CompactTextString(m) }
func (*Pin) ProtoMessage()    {}
func (*Pin) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{11}
}

func (m *Pin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pin.Unmarshal(m, b)
}
func (m *Pin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pin.Marshal(b, m, deterministic)
}
func (m *Pin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pin.Merge(m, src)
}
func (m *Pin) XXX_Size() int {
	return xxx_messageInfo_Pin.Size(m)
}
func (m *Pin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pin.DiscardUnknown(m)
}

var xxx_messageInfo_Pin proto.InternalMessageInfo

func (m *Pin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pin) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Pin) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Pin) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Pin) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Pin) GetPinEnabled() bool {
	if m != nil {
		return m.PinEnabled
	}
	return false
}

func (m *Pin) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type Privacy struct {
	Id                    int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	ActivityStatus        bool                 `protobuf:"varint,5,opt,name=activity_status,json=activityStatus,proto3" json:"activity_status,omitempty"`
	PrivateAccount        bool                 `protobuf:"varint,6,opt,name=private_account,json=privateAccount,proto3" json:"private_account,omitempty"`
	BlockedAccountsId     []*Profile           `protobuf:"bytes,7,rep,name=blocked_accounts_id,json=blockedAccountsId,proto3" json:"blocked_accounts_id,omitempty"`
	MutedAccountsId       []*Profile           `protobuf:"bytes,8,rep,name=muted_accounts_id,json=mutedAccountsId,proto3" json:"muted_accounts_id,omitempty"`
	BlockedTeamAccountsId []*TeamProfile       `protobuf:"bytes,9,rep,name=blocked_team_accounts_id,json=blockedTeamAccountsId,proto3" json:"blocked_team_accounts_id,omitempty"`
	MutedTeamAccountsId   []*TeamProfile       `protobuf:"bytes,10,rep,name=muted_team_accounts_id,json=mutedTeamAccountsId,proto3" json:"muted_team_accounts_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *Privacy) Reset()         { *m = Privacy{} }
func (m *Privacy) String() string { return proto.CompactTextString(m) }
func (*Privacy) ProtoMessage()    {}
func (*Privacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{12}
}

func (m *Privacy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Privacy.Unmarshal(m, b)
}
func (m *Privacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Privacy.Marshal(b, m, deterministic)
}
func (m *Privacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Privacy.Merge(m, src)
}
func (m *Privacy) XXX_Size() int {
	return xxx_messageInfo_Privacy.Size(m)
}
func (m *Privacy) XXX_DiscardUnknown() {
	xxx_messageInfo_Privacy.DiscardUnknown(m)
}

var xxx_messageInfo_Privacy proto.InternalMessageInfo

func (m *Privacy) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Privacy) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Privacy) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Privacy) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Privacy) GetActivityStatus() bool {
	if m != nil {
		return m.ActivityStatus
	}
	return false
}

func (m *Privacy) GetPrivateAccount() bool {
	if m != nil {
		return m.PrivateAccount
	}
	return false
}

func (m *Privacy) GetBlockedAccountsId() []*Profile {
	if m != nil {
		return m.BlockedAccountsId
	}
	return nil
}

func (m *Privacy) GetMutedAccountsId() []*Profile {
	if m != nil {
		return m.MutedAccountsId
	}
	return nil
}

func (m *Privacy) GetBlockedTeamAccountsId() []*TeamProfile {
	if m != nil {
		return m.BlockedTeamAccountsId
	}
	return nil
}

func (m *Privacy) GetMutedTeamAccountsId() []*TeamProfile {
	if m != nil {
		return m.MutedTeamAccountsId
	}
	return nil
}

type Notification struct {
	Id                      int32                                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt               *timestamp.Timestamp                   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamp.Timestamp                   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt               *timestamp.Timestamp                   `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	PauseAll                bool                                   `protobuf:"varint,5,opt,name=pause_all,json=pauseAll,proto3" json:"pause_all,omitempty"`
	PostAndCommentsId       *PostAndCommentsPushNotification       `protobuf:"bytes,6,opt,name=post_and_comments_id,json=postAndCommentsId,proto3" json:"post_and_comments_id,omitempty"`
	FollowingAndFollowersId *FollowingAndFollowersPushNotification `protobuf:"bytes,7,opt,name=following_and_followers_id,json=followingAndFollowersId,proto3" json:"following_and_followers_id,omitempty"`
	DirectMessagesId        *DirectMessagesPushNotification        `protobuf:"bytes,8,opt,name=direct_messages_id,json=directMessagesId,proto3" json:"direct_messages_id,omitempty"`
	EmailAndSmsId           *EmailAndSmsPushNotification           `protobuf:"bytes,9,opt,name=email_and_sms_id,json=emailAndSmsId,proto3" json:"email_and_sms_id,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                               `json:"-"`
	XXX_unrecognized        []byte                                 `json:"-"`
	XXX_sizecache           int32                                  `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{13}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Notification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Notification) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Notification) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Notification) GetPauseAll() bool {
	if m != nil {
		return m.PauseAll
	}
	return false
}

func (m *Notification) GetPostAndCommentsId() *PostAndCommentsPushNotification {
	if m != nil {
		return m.PostAndCommentsId
	}
	return nil
}

func (m *Notification) GetFollowingAndFollowersId() *FollowingAndFollowersPushNotification {
	if m != nil {
		return m.FollowingAndFollowersId
	}
	return nil
}

func (m *Notification) GetDirectMessagesId() *DirectMessagesPushNotification {
	if m != nil {
		return m.DirectMessagesId
	}
	return nil
}

func (m *Notification) GetEmailAndSmsId() *EmailAndSmsPushNotification {
	if m != nil {
		return m.EmailAndSmsId
	}
	return nil
}

type PostAndCommentsPushNotification struct {
	Id                           int32                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt                    *timestamp.Timestamp           `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                    *timestamp.Timestamp           `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt                    *timestamp.Timestamp           `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Likes                        *TieredPushNotificationSetting `protobuf:"bytes,5,opt,name=likes,proto3" json:"likes,omitempty"`
	LikesAndCommentsOnPostsOfYou *TieredPushNotificationSetting `protobuf:"bytes,6,opt,name=likes_and_comments_on_posts_of_you,json=likesAndCommentsOnPostsOfYou,proto3" json:"likes_and_comments_on_posts_of_you,omitempty"`
	PostsOfYou                   *TieredPushNotificationSetting `protobuf:"bytes,7,opt,name=posts_of_you,json=postsOfYou,proto3" json:"posts_of_you,omitempty"`
	Comments                     *TieredPushNotificationSetting `protobuf:"bytes,8,opt,name=comments,proto3" json:"comments,omitempty"`
	CommentLikes                 *TieredPushNotificationSetting `protobuf:"bytes,9,opt,name=comment_likes,json=commentLikes,proto3" json:"comment_likes,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                       `json:"-"`
	XXX_unrecognized             []byte                         `json:"-"`
	XXX_sizecache                int32                          `json:"-"`
}

func (m *PostAndCommentsPushNotification) Reset()         { *m = PostAndCommentsPushNotification{} }
func (m *PostAndCommentsPushNotification) String() string { return proto.CompactTextString(m) }
func (*PostAndCommentsPushNotification) ProtoMessage()    {}
func (*PostAndCommentsPushNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{14}
}

func (m *PostAndCommentsPushNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAndCommentsPushNotification.Unmarshal(m, b)
}
func (m *PostAndCommentsPushNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAndCommentsPushNotification.Marshal(b, m, deterministic)
}
func (m *PostAndCommentsPushNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAndCommentsPushNotification.Merge(m, src)
}
func (m *PostAndCommentsPushNotification) XXX_Size() int {
	return xxx_messageInfo_PostAndCommentsPushNotification.Size(m)
}
func (m *PostAndCommentsPushNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAndCommentsPushNotification.DiscardUnknown(m)
}

var xxx_messageInfo_PostAndCommentsPushNotification proto.InternalMessageInfo

func (m *PostAndCommentsPushNotification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PostAndCommentsPushNotification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetLikes() *TieredPushNotificationSetting {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetLikesAndCommentsOnPostsOfYou() *TieredPushNotificationSetting {
	if m != nil {
		return m.LikesAndCommentsOnPostsOfYou
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetPostsOfYou() *TieredPushNotificationSetting {
	if m != nil {
		return m.PostsOfYou
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetComments() *TieredPushNotificationSetting {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *PostAndCommentsPushNotification) GetCommentLikes() *TieredPushNotificationSetting {
	if m != nil {
		return m.CommentLikes
	}
	return nil
}

type FollowingAndFollowersPushNotification struct {
	Id                       int32                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt                *timestamp.Timestamp           `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                *timestamp.Timestamp           `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt                *timestamp.Timestamp           `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	FollowerRequests         *PushNotificationSetting       `protobuf:"bytes,5,opt,name=follower_requests,json=followerRequests,proto3" json:"follower_requests,omitempty"`
	AcceptedFollowerRequests *PushNotificationSetting       `protobuf:"bytes,6,opt,name=accepted_follower_requests,json=acceptedFollowerRequests,proto3" json:"accepted_follower_requests,omitempty"`
	MentionsInBio            *TieredPushNotificationSetting `protobuf:"bytes,7,opt,name=mentions_in_bio,json=mentionsInBio,proto3" json:"mentions_in_bio,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                       `json:"-"`
	XXX_unrecognized         []byte                         `json:"-"`
	XXX_sizecache            int32                          `json:"-"`
}

func (m *FollowingAndFollowersPushNotification) Reset()         { *m = FollowingAndFollowersPushNotification{} }
func (m *FollowingAndFollowersPushNotification) String() string { return proto.CompactTextString(m) }
func (*FollowingAndFollowersPushNotification) ProtoMessage()    {}
func (*FollowingAndFollowersPushNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{15}
}

func (m *FollowingAndFollowersPushNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingAndFollowersPushNotification.Unmarshal(m, b)
}
func (m *FollowingAndFollowersPushNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingAndFollowersPushNotification.Marshal(b, m, deterministic)
}
func (m *FollowingAndFollowersPushNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingAndFollowersPushNotification.Merge(m, src)
}
func (m *FollowingAndFollowersPushNotification) XXX_Size() int {
	return xxx_messageInfo_FollowingAndFollowersPushNotification.Size(m)
}
func (m *FollowingAndFollowersPushNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingAndFollowersPushNotification.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingAndFollowersPushNotification proto.InternalMessageInfo

func (m *FollowingAndFollowersPushNotification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FollowingAndFollowersPushNotification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FollowingAndFollowersPushNotification) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *FollowingAndFollowersPushNotification) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *FollowingAndFollowersPushNotification) GetFollowerRequests() *PushNotificationSetting {
	if m != nil {
		return m.FollowerRequests
	}
	return nil
}

func (m *FollowingAndFollowersPushNotification) GetAcceptedFollowerRequests() *PushNotificationSetting {
	if m != nil {
		return m.AcceptedFollowerRequests
	}
	return nil
}

func (m *FollowingAndFollowersPushNotification) GetMentionsInBio() *TieredPushNotificationSetting {
	if m != nil {
		return m.MentionsInBio
	}
	return nil
}

type DirectMessagesPushNotification struct {
	Id                   int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp     `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp     `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp     `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	MessageRequests      *PushNotificationSetting `protobuf:"bytes,5,opt,name=message_requests,json=messageRequests,proto3" json:"message_requests,omitempty"`
	Message              *PushNotificationSetting `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	GroupRequests        *PushNotificationSetting `protobuf:"bytes,7,opt,name=group_requests,json=groupRequests,proto3" json:"group_requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DirectMessagesPushNotification) Reset()         { *m = DirectMessagesPushNotification{} }
func (m *DirectMessagesPushNotification) String() string { return proto.CompactTextString(m) }
func (*DirectMessagesPushNotification) ProtoMessage()    {}
func (*DirectMessagesPushNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{16}
}

func (m *DirectMessagesPushNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectMessagesPushNotification.Unmarshal(m, b)
}
func (m *DirectMessagesPushNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectMessagesPushNotification.Marshal(b, m, deterministic)
}
func (m *DirectMessagesPushNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectMessagesPushNotification.Merge(m, src)
}
func (m *DirectMessagesPushNotification) XXX_Size() int {
	return xxx_messageInfo_DirectMessagesPushNotification.Size(m)
}
func (m *DirectMessagesPushNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectMessagesPushNotification.DiscardUnknown(m)
}

var xxx_messageInfo_DirectMessagesPushNotification proto.InternalMessageInfo

func (m *DirectMessagesPushNotification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DirectMessagesPushNotification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DirectMessagesPushNotification) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *DirectMessagesPushNotification) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *DirectMessagesPushNotification) GetMessageRequests() *PushNotificationSetting {
	if m != nil {
		return m.MessageRequests
	}
	return nil
}

func (m *DirectMessagesPushNotification) GetMessage() *PushNotificationSetting {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *DirectMessagesPushNotification) GetGroupRequests() *PushNotificationSetting {
	if m != nil {
		return m.GroupRequests
	}
	return nil
}

type EmailAndSmsPushNotification struct {
	Id                   int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp     `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp     `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp     `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	FeedbackEmail        *PushNotificationSetting `protobuf:"bytes,5,opt,name=feedback_email,json=feedbackEmail,proto3" json:"feedback_email,omitempty"`
	ReminderEmails       *PushNotificationSetting `protobuf:"bytes,6,opt,name=reminder_emails,json=reminderEmails,proto3" json:"reminder_emails,omitempty"`
	ProductEmails        *PushNotificationSetting `protobuf:"bytes,7,opt,name=product_emails,json=productEmails,proto3" json:"product_emails,omitempty"`
	NewsEmails           *PushNotificationSetting `protobuf:"bytes,8,opt,name=news_emails,json=newsEmails,proto3" json:"news_emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EmailAndSmsPushNotification) Reset()         { *m = EmailAndSmsPushNotification{} }
func (m *EmailAndSmsPushNotification) String() string { return proto.CompactTextString(m) }
func (*EmailAndSmsPushNotification) ProtoMessage()    {}
func (*EmailAndSmsPushNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{17}
}

func (m *EmailAndSmsPushNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAndSmsPushNotification.Unmarshal(m, b)
}
func (m *EmailAndSmsPushNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAndSmsPushNotification.Marshal(b, m, deterministic)
}
func (m *EmailAndSmsPushNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAndSmsPushNotification.Merge(m, src)
}
func (m *EmailAndSmsPushNotification) XXX_Size() int {
	return xxx_messageInfo_EmailAndSmsPushNotification.Size(m)
}
func (m *EmailAndSmsPushNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAndSmsPushNotification.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAndSmsPushNotification proto.InternalMessageInfo

func (m *EmailAndSmsPushNotification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EmailAndSmsPushNotification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EmailAndSmsPushNotification) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *EmailAndSmsPushNotification) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *EmailAndSmsPushNotification) GetFeedbackEmail() *PushNotificationSetting {
	if m != nil {
		return m.FeedbackEmail
	}
	return nil
}

func (m *EmailAndSmsPushNotification) GetReminderEmails() *PushNotificationSetting {
	if m != nil {
		return m.ReminderEmails
	}
	return nil
}

func (m *EmailAndSmsPushNotification) GetProductEmails() *PushNotificationSetting {
	if m != nil {
		return m.ProductEmails
	}
	return nil
}

func (m *EmailAndSmsPushNotification) GetNewsEmails() *PushNotificationSetting {
	if m != nil {
		return m.NewsEmails
	}
	return nil
}

type TieredPushNotificationSetting struct {
	Off                  bool     `protobuf:"varint,1,opt,name=Off,proto3" json:"Off,omitempty"`
	FromPeopleIFollow    bool     `protobuf:"varint,2,opt,name=FromPeopleIFollow,proto3" json:"FromPeopleIFollow,omitempty"`
	FromEveryone         bool     `protobuf:"varint,3,opt,name=FromEveryone,proto3" json:"FromEveryone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TieredPushNotificationSetting) Reset()         { *m = TieredPushNotificationSetting{} }
func (m *TieredPushNotificationSetting) String() string { return proto.CompactTextString(m) }
func (*TieredPushNotificationSetting) ProtoMessage()    {}
func (*TieredPushNotificationSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{18}
}

func (m *TieredPushNotificationSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TieredPushNotificationSetting.Unmarshal(m, b)
}
func (m *TieredPushNotificationSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TieredPushNotificationSetting.Marshal(b, m, deterministic)
}
func (m *TieredPushNotificationSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TieredPushNotificationSetting.Merge(m, src)
}
func (m *TieredPushNotificationSetting) XXX_Size() int {
	return xxx_messageInfo_TieredPushNotificationSetting.Size(m)
}
func (m *TieredPushNotificationSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_TieredPushNotificationSetting.DiscardUnknown(m)
}

var xxx_messageInfo_TieredPushNotificationSetting proto.InternalMessageInfo

func (m *TieredPushNotificationSetting) GetOff() bool {
	if m != nil {
		return m.Off
	}
	return false
}

func (m *TieredPushNotificationSetting) GetFromPeopleIFollow() bool {
	if m != nil {
		return m.FromPeopleIFollow
	}
	return false
}

func (m *TieredPushNotificationSetting) GetFromEveryone() bool {
	if m != nil {
		return m.FromEveryone
	}
	return false
}

type PushNotificationSetting struct {
	Off                  bool     `protobuf:"varint,1,opt,name=Off,proto3" json:"Off,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=On,proto3" json:"On,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushNotificationSetting) Reset()         { *m = PushNotificationSetting{} }
func (m *PushNotificationSetting) String() string { return proto.CompactTextString(m) }
func (*PushNotificationSetting) ProtoMessage()    {}
func (*PushNotificationSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1cda5cb3f8b1cc6, []int{19}
}

func (m *PushNotificationSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushNotificationSetting.Unmarshal(m, b)
}
func (m *PushNotificationSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushNotificationSetting.Marshal(b, m, deterministic)
}
func (m *PushNotificationSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushNotificationSetting.Merge(m, src)
}
func (m *PushNotificationSetting) XXX_Size() int {
	return xxx_messageInfo_PushNotificationSetting.Size(m)
}
func (m *PushNotificationSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_PushNotificationSetting.DiscardUnknown(m)
}

var xxx_messageInfo_PushNotificationSetting proto.InternalMessageInfo

func (m *PushNotificationSetting) GetOff() bool {
	if m != nil {
		return m.Off
	}
	return false
}

func (m *PushNotificationSetting) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func init() {
	proto.RegisterEnum("InvestorType", InvestorType_name, InvestorType_value)
	proto.RegisterEnum("InvestmentStage", InvestmentStage_name, InvestmentStage_value)
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*Group)(nil), "Group")
	proto.RegisterType((*Team)(nil), "Team")
	proto.RegisterType((*TeamProfile)(nil), "TeamProfile")
	proto.RegisterType((*InvestorDetail)(nil), "InvestorDetail")
	proto.RegisterType((*StartupDetail)(nil), "StartupDetail")
	proto.RegisterType((*Settings)(nil), "Settings")
	proto.RegisterType((*LoginActivity)(nil), "LoginActivity")
	proto.RegisterType((*Payments)(nil), "Payments")
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterType((*Pin)(nil), "Pin")
	proto.RegisterType((*Privacy)(nil), "Privacy")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*PostAndCommentsPushNotification)(nil), "PostAndCommentsPushNotification")
	proto.RegisterType((*FollowingAndFollowersPushNotification)(nil), "FollowingAndFollowersPushNotification")
	proto.RegisterType((*DirectMessagesPushNotification)(nil), "DirectMessagesPushNotification")
	proto.RegisterType((*EmailAndSmsPushNotification)(nil), "EmailAndSmsPushNotification")
	proto.RegisterType((*TieredPushNotificationSetting)(nil), "TieredPushNotificationSetting")
	proto.RegisterType((*PushNotificationSetting)(nil), "PushNotificationSetting")
}

func init() {
	proto.RegisterFile("proto/tables.proto", fileDescriptor_b1cda5cb3f8b1cc6)
}

var fileDescriptor_b1cda5cb3f8b1cc6 = []byte{
	// 2794 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5a, 0xdd, 0x6e, 0xdc, 0xc6,
	0xf5, 0xcf, 0x6a, 0xbf, 0xb8, 0x67, 0x3f, 0x35, 0xb2, 0xe5, 0x8d, 0xec, 0x58, 0x2b, 0xc5, 0x71,
	0x14, 0xe3, 0xef, 0xd5, 0xbf, 0x6a, 0x9a, 0xc4, 0x0e, 0x82, 0x54, 0x76, 0xa4, 0x62, 0x81, 0xd8,
	0x56, 0x29, 0xa7, 0x68, 0x73, 0x43, 0xcc, 0x92, 0xb3, 0xab, 0x81, 0xc8, 0x21, 0xc3, 0x19, 0xca,
	0x5e, 0x5f, 0xb6, 0x17, 0x6d, 0x1f, 0xa0, 0x0f, 0x52, 0x14, 0x68, 0x91, 0xbc, 0x44, 0x81, 0x02,
	0xb9, 0x2b, 0x90, 0x22, 0x97, 0x7d, 0x83, 0xf6, 0xaa, 0x98, 0x0f, 0x72, 0xc9, 0x95, 0xe2, 0x75,
	0x0a, 0xf4, 0x46, 0xc8, 0x95, 0xc8, 0xdf, 0xf9, 0x9d, 0x33, 0xb3, 0x73, 0xce, 0x9c, 0x73, 0x66,
	0x28, 0x40, 0x51, 0x1c, 0x8a, 0x70, 0x57, 0xe0, 0xb1, 0x4f, 0xf8, 0x50, 0xbd, 0x6c, 0xdc, 0x9f,
	0x52, 0x71, 0x92, 0x8c, 0x87, 0x6e, 0x18, 0xec, 0x52, 0x36, 0x09, 0xc7, 0x7e, 0xf8, 0x3c, 0x8c,
	0x08, 0xdb, 0x55, 0x62, 0xf7, 0xee, 0x94, 0xb0, 0xbb, 0xd3, 0x30, 0x0e, 0x76, 0xc3, 0x48, 0xd0,
	0x90, 0xf1, 0x5d, 0xf9, 0x62, 0x74, 0xdf, 0xcb, 0xe9, 0x06, 0xcf, 0xa8, 0x38, 0x0d, 0x9f, 0xed,
	0x4e, 0xc3, 0xbb, 0x4a, 0x78, 0xf7, 0x0c, 0xfb, 0xd4, 0xc3, 0x22, 0x8c, 0xf9, 0x6e, 0xf6, 0x68,
	0xf4, 0xde, 0xcf, 0xe9, 0x29, 0x64, 0x9c, 0x4c, 0x76, 0x79, 0xec, 0xee, 0x4e, 0xc3, 0x70, 0xea,
	0x93, 0x39, 0x26, 0x68, 0x40, 0xb8, 0xc0, 0x41, 0x64, 0x14, 0xcd, 0x0f, 0x70, 0xc3, 0x20, 0x08,
	0x99, 0xc6, 0xb6, 0xff, 0x56, 0x87, 0xca, 0x67, 0x9c, 0xc4, 0x68, 0x0b, 0x56, 0xa8, 0xd7, 0x2f,
	0x0d, 0x4a, 0x3b, 0xd5, 0x07, 0xab, 0x5f, 0x7d, 0xf9, 0x7a, 0x1b, 0x9a, 0xa8, 0x4e, 0x99, 0x20,
	0x53, 0x12, 0xef, 0x94, 0xec, 0x15, 0xea, 0xa1, 0x7b, 0x00, 0x6e, 0x4c, 0xb0, 0x20, 0x9e, 0x83,
	0x45, 0x7f, 0x65, 0x50, 0xda, 0x69, 0xee, 0x6d, 0x0c, 0xf5, 0xa8, 0xc3, 0x74, 0xd4, 0xe1, 0xd3,
	0x74, 0x54, 0xbb, 0x61, 0xd8, 0xfb, 0x42, 0xaa, 0x7a, 0xc4, 0x27, 0x46, 0xb5, 0xbc, 0x5c, 0xd5,
	0xb0, 0xb5, 0x6a, 0x12, 0x79, 0xe9, 0xa8, 0x95, 0xe5, 0xaa, 0x86, 0xbd, 0x2f, 0xd0, 0x1d, 0x58,
	0x4d, 0x38, 0x89, 0x1d, 0xec, 0xba, 0x61, 0xc2, 0x84, 0x23, 0x66, 0x11, 0xe9, 0x57, 0x07, 0xa5,
	0x9d, 0x86, 0xdd, 0x95, 0x82, 0x7d, 0x8d, 0x3f, 0x9d, 0x45, 0x04, 0xbd, 0x0d, 0x30, 0xa1, 0x31,
	0x17, 0x0e, 0xc3, 0x01, 0xe9, 0xd7, 0x24, 0xe9, 0x81, 0xf5, 0xed, 0x37, 0x9b, 0x95, 0x41, 0xe9,
	0x97, 0x25, 0xbb, 0xa1, 0x64, 0x8f, 0x71, 0x40, 0xd0, 0x5b, 0xd0, 0xf0, 0x71, 0xca, 0xab, 0x2f,
	0xf0, 0x2c, 0x29, 0x4a, 0x69, 0x6a, 0x6c, 0x45, 0xb3, 0x16, 0x69, 0x52, 0xa4, 0x68, 0x37, 0xa1,
	0x36, 0x25, 0xcc, 0x23, 0x71, 0xbf, 0xa1, 0x38, 0xb5, 0x6f, 0xbf, 0xd9, 0x5c, 0x19, 0x94, 0x6c,
	0x83, 0xa2, 0x1b, 0x72, 0x34, 0x36, 0x4d, 0xf0, 0x94, 0xf0, 0x3e, 0xa8, 0xa9, 0xcf, 0x01, 0x74,
	0x1b, 0xac, 0x08, 0x73, 0xfe, 0x2c, 0x8c, 0xbd, 0x7e, 0x53, 0xe9, 0xc3, 0xb7, 0xdf, 0x6c, 0xd6,
	0xe4, 0x18, 0x11, 0xd8, 0x99, 0x0c, 0xdd, 0x03, 0x94, 0x3e, 0x3b, 0x6e, 0xc8, 0x26, 0x34, 0x0e,
	0x88, 0xd7, 0x6f, 0x9d, 0xd3, 0x58, 0x4d, 0x59, 0x0f, 0x53, 0x12, 0xea, 0x43, 0x19, 0x4f, 0x49,
	0xbf, 0xad, 0x02, 0x23, 0x9d, 0x9d, 0x84, 0xd0, 0x5b, 0x00, 0x63, 0x1a, 0x8b, 0x13, 0x47, 0x2e,
	0x77, 0xbf, 0x53, 0x98, 0x7e, 0x43, 0x49, 0x3e, 0xc1, 0x82, 0xa0, 0x77, 0xa0, 0x15, 0x9d, 0x84,
	0x8c, 0x38, 0x2c, 0x09, 0xc6, 0x24, 0xee, 0x77, 0x0b, 0xc4, 0xa6, 0x92, 0x3d, 0x56, 0x22, 0x74,
	0x13, 0xaa, 0x24, 0xc0, 0xd4, 0xef, 0xf7, 0x16, 0xd6, 0x4b, 0xc3, 0x68, 0x00, 0x35, 0x19, 0x91,
	0x4c, 0xf4, 0x57, 0x17, 0x08, 0x06, 0x47, 0xbb, 0x00, 0x51, 0x1c, 0x4e, 0xa8, 0x4f, 0x1c, 0xea,
	0xf5, 0x91, 0x0a, 0x16, 0x6b, 0x78, 0xa4, 0xa1, 0x07, 0xb5, 0xaf, 0xbe, 0x7c, 0x7d, 0x65, 0xfb,
	0x35, 0xbb, 0x61, 0x38, 0x23, 0x0f, 0x6d, 0x42, 0x33, 0x26, 0x9c, 0x08, 0x47, 0x84, 0xa7, 0x84,
	0xf5, 0xd7, 0xd4, 0x0a, 0x83, 0x82, 0x9e, 0x4a, 0x04, 0x1d, 0xc1, 0x7a, 0x8e, 0xe0, 0x90, 0xe7,
	0x11, 0x8d, 0xb1, 0xdc, 0xcb, 0xfd, 0x2b, 0x4b, 0x43, 0xf1, 0xca, 0xdc, 0xce, 0x41, 0xa6, 0x87,
	0xee, 0x41, 0x8f, 0x27, 0x63, 0xee, 0xc6, 0x54, 0xe7, 0x04, 0x39, 0xd3, 0xab, 0x83, 0xf2, 0x4e,
	0x73, 0xaf, 0x33, 0x3c, 0xce, 0x0b, 0xec, 0x6e, 0x81, 0x37, 0xf2, 0xd0, 0x75, 0x68, 0x50, 0xee,
	0x60, 0x57, 0xd0, 0x33, 0xd2, 0x5f, 0x1f, 0x94, 0x76, 0x2c, 0xdb, 0xa2, 0x7c, 0x5f, 0xbd, 0xdf,
	0xb7, 0xbe, 0xfa, 0xf2, 0xf5, 0x8a, 0x55, 0x1a, 0x94, 0xb6, 0xbf, 0xae, 0x42, 0xdd, 0xfc, 0xe6,
	0x4b, 0xb9, 0xaf, 0x7b, 0x50, 0x1e, 0xd3, 0xd0, 0xec, 0x64, 0xf9, 0x88, 0x3e, 0x80, 0x36, 0x79,
	0x1e, 0x91, 0x98, 0x12, 0xe6, 0x2a, 0xd7, 0xd7, 0xd4, 0x82, 0x36, 0x87, 0x07, 0x19, 0xaa, 0xbd,
	0xbf, 0xf7, 0x9a, 0xdd, 0x9a, 0x33, 0x47, 0x9e, 0x8c, 0x18, 0xec, 0x79, 0x31, 0xe1, 0xca, 0x0f,
	0x75, 0x13, 0x31, 0xfb, 0x1a, 0x9a, 0x47, 0x8c, 0xe1, 0x8c, 0x3c, 0xf4, 0x13, 0x68, 0x11, 0x2f,
	0x71, 0x95, 0x2f, 0xa5, 0x8a, 0xa5, 0x46, 0x82, 0xe1, 0x41, 0x0a, 0x66, 0x4a, 0xcd, 0x8c, 0x37,
	0xf2, 0xd0, 0x3a, 0xd4, 0xf8, 0x29, 0xf5, 0x7d, 0xde, 0x6f, 0x0c, 0xca, 0x3b, 0x0d, 0xdb, 0xbc,
	0xa1, 0xdb, 0x50, 0x17, 0x04, 0x07, 0xd2, 0x12, 0xa8, 0xc1, 0xab, 0xc3, 0xa7, 0x04, 0x07, 0x99,
	0x91, 0x9a, 0x94, 0x8e, 0x3c, 0xf4, 0x0e, 0x58, 0xd3, 0x38, 0x4c, 0x22, 0x49, 0x6c, 0xaa, 0x21,
	0x6b, 0xc3, 0x9f, 0x49, 0x20, 0xfb, 0x5d, 0x75, 0x25, 0x1f, 0x79, 0xe8, 0x7d, 0x68, 0xf1, 0xd0,
	0xa5, 0xd8, 0x77, 0x02, 0xe2, 0x51, 0xac, 0xf6, 0x79, 0x73, 0xaf, 0x35, 0x3c, 0x56, 0xe0, 0x23,
	0x89, 0xcd, 0xe7, 0xc8, 0xe7, 0x20, 0xda, 0x83, 0x26, 0x27, 0x42, 0x50, 0x36, 0x55, 0x8b, 0xd1,
	0x56, 0x7a, 0x8d, 0xe1, 0xb1, 0xc1, 0x32, 0x25, 0x48, 0x59, 0x23, 0x0f, 0x6d, 0x41, 0x2b, 0xdd,
	0x71, 0x2a, 0xbd, 0xaa, 0x3c, 0x60, 0x37, 0x0d, 0xa6, 0x52, 0xeb, 0x00, 0x9a, 0x4c, 0x2d, 0x03,
	0xf6, 0xa9, 0x98, 0xe9, 0x04, 0x60, 0xe7, 0x21, 0xf4, 0x06, 0x00, 0x3e, 0xc3, 0x02, 0xc7, 0x4e,
	0x12, 0x9b, 0xdd, 0x6f, 0x37, 0x34, 0xf2, 0x59, 0xec, 0xdf, 0x57, 0xe3, 0x5a, 0xa5, 0xed, 0xdf,
	0x57, 0xa0, 0xaa, 0x7e, 0xf3, 0xa5, 0x8c, 0xea, 0x1b, 0x50, 0x99, 0x17, 0xa8, 0x5c, 0x6e, 0x53,
	0xa8, 0x94, 0x5e, 0x58, 0x99, 0x14, 0x8a, 0x36, 0xf4, 0x8e, 0x58, 0x2c, 0x47, 0x6a, 0x6f, 0xdc,
	0x80, 0xca, 0x53, 0x3c, 0xe5, 0x2a, 0x50, 0x0b, 0x9a, 0x12, 0x95, 0x35, 0x52, 0x27, 0x66, 0x27,
	0x9c, 0x38, 0x01, 0x91, 0x4f, 0x5c, 0xd5, 0xa2, 0xaa, 0xdd, 0xd5, 0x82, 0x27, 0x93, 0x47, 0x1a,
	0x46, 0x77, 0xa0, 0xad, 0x63, 0x30, 0xe5, 0x81, 0x0a, 0xc4, 0xea, 0x50, 0x76, 0x10, 0x76, 0x4b,
	0xc9, 0x52, 0xee, 0x06, 0x58, 0x94, 0x1f, 0x25, 0x63, 0x9f, 0xba, 0xaa, 0x34, 0xa9, 0x4c, 0xa5,
	0xdf, 0xd1, 0x75, 0xa8, 0xee, 0x7b, 0x01, 0x65, 0x26, 0x32, 0x8d, 0xbe, 0xc6, 0x16, 0x62, 0xa1,
	0xfd, 0x5d, 0xb1, 0xf0, 0x3b, 0x0b, 0x2a, 0x72, 0xa3, 0x5c, 0xd6, 0x50, 0x50, 0xce, 0xae, 0x5e,
	0xe8, 0x6c, 0x19, 0x28, 0xd2, 0xa1, 0xb5, 0x45, 0x87, 0x4a, 0x74, 0x5e, 0x44, 0xeb, 0x17, 0x17,
	0xd1, 0x34, 0xcc, 0xac, 0x0b, 0xc3, 0xec, 0x16, 0x58, 0x94, 0x79, 0x09, 0x17, 0xf1, 0xcc, 0x74,
	0x24, 0xb9, 0xae, 0x25, 0x95, 0xa0, 0x8f, 0xa0, 0x35, 0x09, 0x13, 0xe6, 0x11, 0x4f, 0x17, 0x7f,
	0x58, 0xfa, 0xe3, 0x9a, 0x86, 0xaf, 0x5a, 0x82, 0x21, 0xac, 0xcd, 0x63, 0x8e, 0x04, 0x91, 0x1f,
	0xce, 0x08, 0xe1, 0x2a, 0x4c, 0xaa, 0xf6, 0x6a, 0x1a, 0x75, 0x07, 0xa9, 0x00, 0xfd, 0x08, 0xba,
	0x27, 0x04, 0x7b, 0x5f, 0x24, 0x38, 0x16, 0x24, 0x56, 0xb9, 0xa9, 0x55, 0x4c, 0xd4, 0x76, 0x27,
	0x4f, 0x50, 0x75, 0xbd, 0x9e, 0x06, 0x69, 0x3b, 0x1f, 0xa4, 0x29, 0x8a, 0xb6, 0xc0, 0xc2, 0xde,
	0x19, 0xe5, 0x61, 0xcc, 0xfb, 0x9d, 0x3c, 0x23, 0x83, 0xd1, 0xee, 0x42, 0x1e, 0xed, 0x9e, 0xcf,
	0xa3, 0xc5, 0xfc, 0xb9, 0xb5, 0xd0, 0xea, 0xf4, 0x4c, 0x2e, 0xcc, 0xb5, 0x38, 0x1b, 0xb9, 0x8e,
	0x4d, 0x35, 0x31, 0xb9, 0x2e, 0xed, 0x5d, 0xe8, 0xaa, 0x52, 0x70, 0xae, 0x83, 0x69, 0xa9, 0x92,
	0x60, 0x2a, 0xba, 0xdd, 0x16, 0xf3, 0x97, 0x91, 0xd4, 0x6a, 0x17, 0xda, 0x84, 0xfe, 0xda, 0x85,
	0xbd, 0x44, 0x91, 0x54, 0xec, 0x24, 0xae, 0x14, 0x3b, 0x89, 0xc5, 0xa6, 0xe8, 0xea, 0xf7, 0x68,
	0x8a, 0xd6, 0xff, 0xcb, 0xa6, 0x68, 0x20, 0xdd, 0x11, 0x50, 0x55, 0x51, 0xaf, 0xe5, 0xb3, 0x42,
	0x5d, 0xc1, 0x23, 0x2f, 0x2d, 0xfa, 0xfd, 0xac, 0xe8, 0x67, 0xa9, 0xe0, 0x4f, 0x65, 0x68, 0xe6,
	0x16, 0xe8, 0x92, 0x1e, 0x65, 0x0a, 0xa5, 0xb9, 0xba, 0x50, 0x9a, 0x0b, 0x25, 0xf9, 0x23, 0x40,
	0x94, 0x9d, 0x11, 0x2e, 0xc2, 0xd8, 0xf1, 0x88, 0xc0, 0xd4, 0xd7, 0x1d, 0x91, 0x54, 0xe9, 0x0e,
	0x47, 0x46, 0xf4, 0x89, 0x92, 0xd8, 0x3d, 0x5a, 0x78, 0x1f, 0x79, 0xe8, 0x3e, 0xac, 0x72, 0x81,
	0x63, 0x91, 0x44, 0x39, 0x6d, 0xdd, 0x18, 0x75, 0x86, 0xc7, 0x5a, 0x62, 0x94, 0xbb, 0x3c, 0xff,
	0xaa, 0xba, 0x01, 0x4b, 0xed, 0x15, 0xdd, 0x18, 0x95, 0x54, 0x97, 0xa2, 0x37, 0x4a, 0x5d, 0xe1,
	0x23, 0x2f, 0xf3, 0xda, 0x1f, 0x2a, 0xd0, 0x29, 0xce, 0x25, 0xe7, 0xb8, 0xf6, 0xa5, 0x71, 0xdc,
	0x1e, 0xb4, 0x33, 0x67, 0x64, 0xe5, 0xbd, 0xb3, 0xd7, 0xce, 0xfc, 0x20, 0x5b, 0x24, 0xbb, 0x45,
	0x73, 0x6f, 0xe8, 0x43, 0x30, 0x5e, 0x09, 0x08, 0x13, 0x0e, 0x17, 0xf2, 0x00, 0x56, 0x53, 0x6a,
	0x3d, 0xa3, 0x26, 0x05, 0xc7, 0x12, 0xb7, 0xbb, 0xb4, 0x08, 0xa0, 0xdb, 0xd0, 0xcd, 0x25, 0xd7,
	0xe7, 0x54, 0x70, 0xe5, 0xbc, 0xaa, 0xdd, 0xce, 0x12, 0xab, 0x04, 0xd1, 0x1e, 0x5c, 0x9d, 0xf3,
	0xe6, 0x46, 0xb8, 0xf2, 0x5b, 0xd5, 0x5e, 0x4b, 0xd9, 0xf3, 0x01, 0x79, 0xd1, 0xf6, 0x24, 0x61,
	0x5e, 0xda, 0x2a, 0x64, 0xb6, 0x0f, 0x25, 0x88, 0xf6, 0xa0, 0x93, 0xb3, 0xa8, 0x7b, 0x5b, 0xdd,
	0x8f, 0xcf, 0xad, 0xd9, 0xed, 0x1c, 0x25, 0x17, 0x17, 0xff, 0x2e, 0x43, 0xbb, 0x10, 0x65, 0x97,
	0x32, 0x2c, 0xde, 0x84, 0xb6, 0x08, 0x05, 0xf6, 0xd5, 0x2a, 0x52, 0x36, 0x55, 0x61, 0x51, 0xb5,
	0x5b, 0x0a, 0x3c, 0xd4, 0x18, 0xfa, 0x7f, 0xb8, 0xe2, 0x63, 0x41, 0xb8, 0x70, 0x62, 0x59, 0x3d,
	0x33, 0x6e, 0x4d, 0x71, 0x91, 0x96, 0xd9, 0x52, 0x94, 0x6a, 0x6c, 0x41, 0x2b, 0xaf, 0xa1, 0x7b,
	0x00, 0xbb, 0x99, 0x63, 0xa2, 0x47, 0x70, 0xb5, 0x60, 0x94, 0x30, 0x53, 0xc4, 0xad, 0xa5, 0xf3,
	0xcf, 0x8f, 0x78, 0xc0, 0x74, 0x2d, 0xdf, 0x82, 0x96, 0x99, 0x96, 0x0e, 0xef, 0x86, 0x1e, 0xd1,
	0x60, 0x2a, 0x9c, 0xb7, 0xa0, 0xe5, 0x86, 0x41, 0x84, 0xd9, 0x4c, 0xdf, 0x86, 0xe8, 0x6b, 0x8c,
	0xa6, 0xc1, 0x1e, 0xe3, 0x80, 0x64, 0xce, 0xff, 0x7b, 0x19, 0xac, 0x34, 0xa7, 0xfd, 0xef, 0xf3,
	0x78, 0xce, 0x79, 0xe5, 0xef, 0xe3, 0xbc, 0x62, 0xc8, 0x54, 0xbe, 0x67, 0xc8, 0xa8, 0xdb, 0x23,
	0x3f, 0x9c, 0x52, 0x66, 0xd2, 0xf8, 0x4b, 0x55, 0x25, 0xfb, 0x53, 0x49, 0x96, 0x5d, 0xd3, 0x5c,
	0xd5, 0xf1, 0x43, 0x7d, 0xb4, 0xd4, 0x07, 0x02, 0x7b, 0x35, 0xe3, 0x7d, 0x6a, 0x04, 0xe8, 0x3d,
	0xe8, 0xb2, 0x50, 0xd0, 0x09, 0x9d, 0x9f, 0x55, 0x75, 0x16, 0x6f, 0x0f, 0x1f, 0xe7, 0x70, 0xbb,
	0x93, 0x67, 0x8d, 0x3c, 0xf4, 0x36, 0x40, 0x14, 0xd3, 0x33, 0xec, 0xce, 0xe6, 0x59, 0xdc, 0x1a,
	0x1e, 0x69, 0xc8, 0x6e, 0x18, 0xd9, 0xc8, 0x43, 0x3b, 0x00, 0x11, 0x9e, 0xa9, 0x1c, 0x45, 0x3d,
	0xe5, 0x78, 0x59, 0x92, 0x8e, 0x34, 0xc4, 0xed, 0x86, 0x11, 0xe6, 0xf6, 0xb6, 0x80, 0xb6, 0x9a,
	0xa3, 0xea, 0x33, 0xe4, 0xc1, 0xef, 0x15, 0x5c, 0x7c, 0x0b, 0xac, 0xec, 0xb7, 0xae, 0x2c, 0x74,
	0x7d, 0x99, 0x04, 0x21, 0xa8, 0xa8, 0x20, 0x2e, 0xab, 0xd5, 0x50, 0xcf, 0xd9, 0xa8, 0xbf, 0x2d,
	0x83, 0x95, 0xce, 0xea, 0x87, 0xa0, 0x2a, 0x06, 0xd5, 0x2d, 0x39, 0xea, 0x98, 0x0a, 0xc7, 0xc5,
	0x71, 0xda, 0x23, 0x54, 0x87, 0x0f, 0x71, 0xec, 0xc9, 0x01, 0xc6, 0x54, 0xc8, 0x47, 0x74, 0x1b,
	0x9a, 0x6e, 0x4c, 0xbc, 0x94, 0x56, 0xcf, 0xd3, 0x40, 0x4b, 0x14, 0x6f, 0x1d, 0xca, 0x11, 0x65,
	0x26, 0x66, 0x2a, 0xc3, 0x23, 0xca, 0x6c, 0x09, 0x64, 0x9e, 0xf8, 0x75, 0x05, 0x2a, 0x8a, 0xf8,
	0x83, 0x17, 0x0a, 0x5e, 0xd8, 0x84, 0xa6, 0x5c, 0xd8, 0xf4, 0xdc, 0xa0, 0xb7, 0x34, 0x48, 0xc8,
	0x1c, 0x1b, 0xde, 0x84, 0x36, 0x27, 0x6e, 0x12, 0x53, 0x31, 0x73, 0xdc, 0xd0, 0x33, 0x17, 0xcf,
	0x76, 0x2b, 0x05, 0x1f, 0x86, 0x1e, 0x41, 0xdb, 0xd0, 0x56, 0x56, 0x5e, 0xd0, 0x48, 0x93, 0x2c,
	0x93, 0x68, 0x71, 0xec, 0x7d, 0x4e, 0x23, 0xc5, 0xb9, 0x0e, 0x8d, 0x49, 0xe2, 0xfb, 0x3a, 0x11,
	0xeb, 0x5c, 0x6d, 0x49, 0x40, 0x5d, 0x46, 0x23, 0xa8, 0xb8, 0x54, 0xcc, 0x4c, 0x82, 0x56, 0xcf,
	0xe8, 0x0a, 0x54, 0xb9, 0x90, 0x3b, 0x4b, 0xdd, 0x2f, 0xdb, 0xfa, 0x05, 0xf5, 0xa1, 0xfe, 0x82,
	0x46, 0x6a, 0x10, 0x75, 0x8b, 0x6c, 0xa7, 0xaf, 0x52, 0x62, 0xee, 0xca, 0xcc, 0xd9, 0x3d, 0x7d,
	0xcd, 0x82, 0xe0, 0xaf, 0x2b, 0x50, 0x3e, 0xa2, 0xec, 0x87, 0x18, 0x38, 0x17, 0x03, 0x11, 0x65,
	0x0e, 0x61, 0x78, 0xec, 0x13, 0xbd, 0x15, 0x2d, 0x1b, 0x22, 0xca, 0x0e, 0x34, 0x22, 0x0f, 0x40,
	0x72, 0x73, 0x69, 0xcf, 0x17, 0xb6, 0xd5, 0x1f, 0x2b, 0x50, 0x37, 0xf9, 0xf9, 0x52, 0xae, 0xea,
	0xdb, 0xd0, 0xc5, 0xa6, 0x62, 0xc8, 0x6e, 0x58, 0x24, 0x5c, 0x2d, 0xad, 0x65, 0x77, 0x52, 0xf8,
	0x58, 0xa1, 0x92, 0xa8, 0xca, 0x93, 0x20, 0xe9, 0x37, 0x1f, 0xb3, 0x8e, 0x1d, 0x03, 0x9b, 0x2f,
	0x3e, 0xe8, 0x03, 0x58, 0x1b, 0xfb, 0xa1, 0x7b, 0x2a, 0x27, 0xa3, 0x21, 0x73, 0xfd, 0x5b, 0xce,
	0x7f, 0x30, 0xb0, 0x57, 0x0d, 0xc9, 0xa8, 0x71, 0x75, 0xdc, 0x5e, 0x0d, 0x12, 0xb1, 0xa0, 0x67,
	0x2d, 0xe8, 0x75, 0x15, 0x25, 0xa7, 0x75, 0x00, 0xfd, 0x74, 0x3c, 0x75, 0xc4, 0xcf, 0x2b, 0x37,
	0x94, 0x72, 0xf1, 0x8c, 0x7f, 0xd5, 0xb0, 0x25, 0x96, 0x33, 0xb3, 0x0f, 0xeb, 0x7a, 0xf0, 0x73,
	0x46, 0xe0, 0x02, 0x23, 0x6b, 0x8a, 0x5b, 0x34, 0x91, 0xc5, 0xcc, 0xd7, 0x15, 0x68, 0xe5, 0xdb,
	0x80, 0x4b, 0x19, 0x38, 0xd7, 0xa1, 0x11, 0xe1, 0x84, 0x13, 0x07, 0xfb, 0xbe, 0x09, 0x19, 0x4b,
	0x01, 0xfb, 0xbe, 0x8f, 0x7e, 0x0e, 0x57, 0xa2, 0x90, 0x0b, 0x07, 0x33, 0xcf, 0x71, 0xc3, 0x20,
	0x3b, 0xaa, 0xe8, 0x22, 0x38, 0x18, 0x1e, 0x85, 0x5c, 0xec, 0x33, 0xef, 0xa1, 0x11, 0x1d, 0x25,
	0xfc, 0xa4, 0xd0, 0x37, 0xad, 0x46, 0x45, 0xc2, 0xc8, 0x43, 0x2e, 0x6c, 0x4c, 0x42, 0xdf, 0x0f,
	0x9f, 0xc9, 0x76, 0x58, 0xda, 0xd5, 0x6f, 0xe6, 0xce, 0x4a, 0x97, 0xcd, 0xdb, 0xc3, 0xc3, 0x94,
	0xb2, 0xcf, 0xbc, 0xc3, 0x94, 0x70, 0xce, 0xfc, 0xb5, 0xc9, 0x45, 0xb4, 0x91, 0x6c, 0xe0, 0x91,
	0x47, 0x63, 0xe2, 0x0a, 0x27, 0x20, 0x9c, 0xe3, 0x29, 0xe1, 0xf3, 0x3e, 0x6d, 0x73, 0xf8, 0x89,
	0x12, 0x3d, 0x32, 0x92, 0x73, 0x56, 0x7b, 0x5e, 0x41, 0xae, 0x42, 0xb3, 0xa7, 0x2e, 0x06, 0xd5,
	0x7c, 0x79, 0xc0, 0xe7, 0xbd, 0xdc, 0x8d, 0xe1, 0x81, 0x14, 0xec, 0x33, 0xef, 0x38, 0x38, 0x6f,
	0xa9, 0x4d, 0xe6, 0xc2, 0x5c, 0x5c, 0xfd, 0xa3, 0x02, 0x9b, 0x4b, 0x56, 0xee, 0x52, 0x86, 0xda,
	0xbb, 0x50, 0xf5, 0xe9, 0x29, 0xe1, 0x26, 0xe9, 0xdf, 0x1c, 0x3e, 0xa5, 0x24, 0x26, 0xde, 0xe2,
	0x6f, 0x37, 0x87, 0x1b, 0x5b, 0x93, 0xd1, 0x09, 0x6c, 0xab, 0x87, 0x62, 0x10, 0x86, 0xcc, 0x91,
	0xb1, 0xc5, 0xe5, 0x29, 0x7b, 0x16, 0x26, 0x26, 0x22, 0x97, 0x99, 0xbc, 0xa1, 0x2c, 0xe5, 0xd6,
	0xfd, 0x09, 0x93, 0x8e, 0xe0, 0x4f, 0x26, 0xbf, 0x0a, 0x13, 0xf4, 0x53, 0x68, 0x15, 0x6c, 0xd6,
	0x5f, 0xc9, 0x26, 0x44, 0x73, 0x0b, 0xf7, 0xc1, 0x4a, 0x67, 0x68, 0xa2, 0x6d, 0x99, 0x76, 0xc6,
	0x47, 0x0f, 0xa1, 0x6d, 0x9e, 0x1d, 0xbd, 0x4a, 0x8d, 0x57, 0x32, 0xd0, 0x32, 0x4a, 0x9f, 0x4a,
	0x9d, 0x2c, 0xc4, 0xfe, 0x59, 0x86, 0xb7, 0x5e, 0x69, 0x0f, 0x5d, 0xca, 0x40, 0x3b, 0x80, 0xd5,
	0x34, 0xab, 0x38, 0x31, 0xf9, 0x22, 0x21, 0x5c, 0xa4, 0x41, 0xd7, 0x1f, 0x7e, 0xd7, 0x42, 0xf6,
	0x52, 0x15, 0xdb, 0x68, 0xa0, 0x5f, 0xc0, 0x06, 0x76, 0x5d, 0x12, 0xc9, 0x29, 0x9c, 0xb7, 0x57,
	0x5b, 0x62, 0xaf, 0x9f, 0xea, 0x1e, 0x2e, 0xda, 0x3d, 0x84, 0xae, 0xf4, 0x98, 0xfe, 0xb0, 0xcd,
	0x9c, 0xf4, 0xab, 0xd4, 0x72, 0x5f, 0xb7, 0x53, 0xb5, 0x11, 0x7b, 0x90, 0xbb, 0xdc, 0xfd, 0x73,
	0x19, 0x6e, 0xbe, 0x3c, 0xa7, 0x5d, 0x4a, 0x2f, 0x3f, 0x84, 0x9e, 0xc9, 0xee, 0xaf, 0xee, 0xe4,
	0xae, 0xd1, 0xc8, 0x7c, 0xb1, 0x07, 0x75, 0x03, 0x2d, 0x75, 0x68, 0x4a, 0x44, 0x1f, 0x43, 0x47,
	0x7f, 0xe3, 0xcb, 0x86, 0xad, 0x2f, 0x51, 0xd5, 0xdf, 0x04, 0xd3, 0x41, 0x33, 0xc7, 0xfd, 0xab,
	0x0c, 0xd7, 0x5f, 0x52, 0x3f, 0x2e, 0xa5, 0xd7, 0x3e, 0x86, 0xce, 0x84, 0x10, 0x6f, 0x8c, 0xdd,
	0x53, 0x47, 0x7f, 0x84, 0x5b, 0xe6, 0xb3, 0x76, 0xca, 0x57, 0x4b, 0x85, 0xf6, 0xa1, 0x1b, 0x93,
	0x80, 0x32, 0x8f, 0xc4, 0xda, 0xc0, 0xf2, 0xad, 0xd8, 0x49, 0x15, 0x94, 0x05, 0x2e, 0xe7, 0x10,
	0xc5, 0xa1, 0x97, 0xb8, 0x22, 0xb5, 0xb0, 0xd4, 0x81, 0x86, 0x6f, 0x0c, 0xdc, 0x83, 0x26, 0x23,
	0xcf, 0x78, 0xaa, 0x6d, 0x2d, 0xd1, 0x06, 0x49, 0xd6, 0xaa, 0x99, 0xef, 0x7f, 0x53, 0x82, 0x37,
	0x5e, 0xba, 0xdb, 0xe5, 0x61, 0xe6, 0xc9, 0x64, 0xa2, 0xdc, 0x6f, 0xd9, 0xf2, 0x11, 0xfd, 0x1f,
	0xac, 0x1e, 0xc6, 0x61, 0x70, 0x44, 0xc2, 0xc8, 0x27, 0x23, 0x9d, 0x57, 0x94, 0xcf, 0x2d, 0xfb,
	0xbc, 0x00, 0x6d, 0x43, 0x4b, 0x82, 0x07, 0x67, 0x24, 0x9e, 0x85, 0x4c, 0xdf, 0xfb, 0x58, 0x76,
	0x01, 0xdb, 0xfe, 0x10, 0xae, 0xbd, 0xfa, 0xf0, 0x1d, 0x58, 0x79, 0xc2, 0xcc, 0x78, 0x2b, 0x4f,
	0xd8, 0x9d, 0x19, 0xb4, 0xf2, 0x37, 0xf4, 0xa8, 0x01, 0xd5, 0x31, 0x66, 0xa7, 0xbc, 0xf7, 0x1a,
	0x5a, 0x83, 0x2e, 0x66, 0x53, 0xe2, 0x3b, 0x29, 0x81, 0xf7, 0x4a, 0xa8, 0x0f, 0x57, 0x22, 0x42,
	0x62, 0x47, 0x84, 0x8e, 0xfa, 0xeb, 0xab, 0xff, 0xdf, 0xe2, 0xbd, 0x15, 0x74, 0x0d, 0xd6, 0xce,
	0x08, 0x13, 0x49, 0x4c, 0x1c, 0x17, 0x47, 0x54, 0x60, 0x9f, 0x72, 0xc1, 0x7b, 0x65, 0xb4, 0x0e,
	0x28, 0x22, 0x31, 0x0f, 0x19, 0xf6, 0x1d, 0x9a, 0x99, 0xaa, 0xdc, 0xf9, 0x4b, 0x09, 0xba, 0x0b,
	0xd7, 0xfc, 0xa8, 0x07, 0x2d, 0x4e, 0x88, 0x97, 0x5a, 0xd0, 0xb3, 0x48, 0x3f, 0xd3, 0xa4, 0x60,
	0x09, 0xdd, 0x82, 0x01, 0xc1, 0xb1, 0x3f, 0x73, 0xf4, 0xff, 0xb2, 0x71, 0xe2, 0x86, 0xb2, 0xab,
	0x93, 0x26, 0x32, 0xd6, 0x0a, 0xda, 0x81, 0x5b, 0xe4, 0x79, 0x84, 0x19, 0xa7, 0x21, 0x4b, 0x39,
	0xe2, 0x84, 0xc6, 0x8b, 0xcc, 0x32, 0xba, 0x0b, 0xef, 0x04, 0xe4, 0xc5, 0x0b, 0xcc, 0x28, 0x23,
	0xce, 0x38, 0xa6, 0xde, 0x94, 0x38, 0x51, 0x4c, 0x9c, 0x48, 0x7d, 0xc8, 0x5f, 0xa0, 0x57, 0x1e,
	0xd4, 0x3f, 0xaf, 0x06, 0xa1, 0x47, 0xfc, 0x71, 0x4d, 0xed, 0x93, 0x1f, 0xff, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x00, 0xaf, 0xdf, 0x44, 0x34, 0x29, 0x00, 0x00,
}
